/**
 * AccordionMenu.test.jsx
 *
 * This test suite verifies the functionality of the AccordionMenu component,
 * which displays three collapsible sections for user-relevant events.
 *
 * ✅ Features Tested:
 * - Renders all three accordion sections:
 *    📚 Upcoming Assignments, 📅 Your Events, 🎉 UNLV Events
 * - Dynamically renders fetched data into each section
 * - View mode toggle (daily ↔ weekly) updates UI correctly
 * - Opens and closes the custom user event modal with appropriate details
 *
 * 🧪 Mocks:
 * - React Bootstrap Accordion to isolate behavior from the UI library
 * - Chrome Extension APIs (chrome.storage and chrome.runtime)
 * - External modules for fetching and filtering event data
 * - Toggle, CanvasAssignments, Events, and UserEventPopup components
 *
 * 🔄 Dependencies:
 * - @testing-library/react for rendering and interaction testing
 * - jest.fn() for mocking state updates and external dependencies
 * - waitFor() and fireEvent() to simulate user interaction and async loading
 *
 * 🛠 Notes:
 * - Custom event click handler uses data-testid="custom-event"
 * - Modal is conditionally rendered when `activeEventPopup` is set
 *
 * Authored by: Sebastian Yepez  
 * CODE AND DOCUMENTATION GENERATED BY CHATGPT 4o
 */

import React from "react";
import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import AccordionMenu from "../components/AccordionMenu";

// Mocks
jest.mock("react-bootstrap/Accordion", () => {
  const RealAccordion = jest.requireActual("react-bootstrap/Accordion");
  return {
    ...RealAccordion,
    Item: ({ children, ...props }) => <div {...props}>{children}</div>,
    Header: ({ children, onClick }) => (
      <div role="button" onClick={onClick}>
        {children}
      </div>
    ),
    Body: ({ children }) => <div>{children}</div>,
  };
});

jest.mock("../components/Toggle", () => ({ isChecked, onChange }) => (
  <button onClick={onChange}>{isChecked ? "Weekly" : "Daily"}</button>
));

jest.mock("../components/CanvasAssignments", () => () => <div>Canvas Assignments</div>);

jest.mock("../components/Events", () => (props) => {
  const { setActiveEventPopup } = props;
  return (
    <div>
      <span
        data-testid="custom-event"
        onClick={() =>
          setActiveEventPopup({
            name: "Test Event",
            startDate: "2025-04-22",
            allDay: false,
            startTime: "14:00",
            endTime: "15:00",
            location: "Test Hall",
            desc: "Test description",
          })
        }
      >
        Custom Event
      </span>
    </div>
  );
});

// ✅ FIXED: Properly mocked popup content
jest.mock("../components/UserEventPopup", () => ({ event, onClose }) => (
  <div>
    <div>📝 Your Event</div>
    <div>{event.name}</div>
    <div>
      {event.allDay
        ? "All-day"
        : "2:00 PM - 3:00 PM"}
    </div>
    <button onClick={onClose}>Close</button>
  </div>
));

// Chrome API mock
global.chrome = {
  storage: {
    sync: {
      get: (keys, cb) => cb({ viewMode: "daily", openKeys: ["0", "1", "2"] }),
      set: jest.fn(),
    },
    local: {
      set: jest.fn(),
    },
  },
  runtime: {
    onMessage: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
    },
  },
};

jest.mock("../../public/scripts/fetch-events.js", () => ({
  fetchEvents: jest.fn().mockResolvedValue([
    [{ name: "AC Event" }],
    [{ name: "IC Event" }],
    [{ name: "RC Event" }],
    [{ name: "UC Event" }],
  ]),
  subscribeToUserEvents: (cb) => {
    cb([{ title: "My Event", startDate: "2025-04-22", startTime: "14:00", allDay: false }]);
    return () => {};
  },
  normalizeUserEvents: (events) =>
    events.map((e) => ({
      ...e,
      name: e.title,
      time: e.allDay ? "(ALL DAY)" : "2:00 PM",
      organization: "Your Event",
      link: "ignore",
    })),
}));

jest.mock("../../public/scripts/filter-events", () => ({
  filterEvents: jest.fn().mockResolvedValue([
    [{ name: "IC Event" }],
    [{ name: "RC Event" }],
    [{ name: "UC Event" }],
  ]),
}));

// ✅ TESTS
describe("AccordionMenu", () => {
  it("renders all three accordion sections", async () => {
    render(<AccordionMenu />);
    await waitFor(() => {
      expect(screen.getByText("📚 Upcoming Assignments")).toBeInTheDocument();
      expect(screen.getByText("📅 Your Events")).toBeInTheDocument();
      expect(screen.getByText("🎉 UNLV Events")).toBeInTheDocument();
    });
  });

  it("renders Events and CanvasAssignments components", async () => {
    render(<AccordionMenu />);
    expect(await screen.findByText("Canvas Assignments")).toBeInTheDocument();
    const events = await screen.findAllByText("Custom Event");
    expect(events[0]).toBeInTheDocument();
});

  it("toggles view mode when Toggle button is clicked", async () => {
    render(<AccordionMenu />);
    const toggle = await screen.findByRole("button", { name: "Daily" });
    fireEvent.click(toggle);
    expect(toggle).toHaveTextContent("Weekly");
  });

  it("opens and closes the user event popup", async () => {
    render(<AccordionMenu />);
    await waitFor(() => {
      expect(screen.getByText("📚 Upcoming Assignments")).toBeInTheDocument();
    });
  
    const customEvents = await screen.findAllByTestId("custom-event");
    fireEvent.click(customEvents[0]); // click the first matching event
  
    expect(await screen.findByText("📝 Your Event")).toBeInTheDocument();
    expect(screen.getByText("Test Event")).toBeInTheDocument();
    expect(screen.getByText("2:00 PM - 3:00 PM")).toBeInTheDocument();
  
    const closeBtn = screen.getByText("Close");
    fireEvent.click(closeBtn);
  
    await waitFor(() =>
      expect(screen.queryByText("📝 Your Event")).not.toBeInTheDocument()
    );
  });
  
});
