/**
 * NotificationToggle Component
 *
 * A reusable toggle switch component for enabling or disabling notifications 
 * within the Rebel Remind extension. This toggle uses `react-switch` and displays 
 * an intuitive bell icon (`FaBell`) when enabled and a slashed bell (`FaBellSlash`) when disabled.
 *
 * Features:
 * - Custom toggle switch with color styling and icon-based feedback
 * - Uses the `react-switch` library for smooth toggle animations
 * - Accepts `enabled` state and `setEnabled` setter function as props for state control
 * - Visually reflects the current notification state through icons and color changes
 *
 * Props:
 * - `enabled` (boolean): Current state of the toggle (true = enabled, false = disabled)
 * - `setEnabled` (function): Callback function to update the toggle state
 *
 * Utilizes:
 * - `FaBell` and `FaBellSlash` from `react-icons/fa` for visual indicators
 * - `react-switch` for the toggle UI
 *
 * Authored by: Billy Estrada
 * Documentation generated by ChatGPT 4o
 *
 * @component
 * @returns {JSX.Element} A styled toggle switch for controlling notification preferences.
 */

import React from "react";
import { FaBell, FaBellSlash } from "react-icons/fa";
import Switch from "react-switch";


function NotificationToggle ({ enabled, setEnabled }) {
    const handleChange = (checked) => {
        setEnabled(checked);
      };
    return (
        <Switch
            onChange={handleChange}
            checked={enabled}
            offColor="#bbb"
            onColor="#8b0000"
            uncheckedIcon={false}
            checkedIcon={false}
            handleDiameter={30}
            height={40}
            width={80}
            handleStyle={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            }}
            uncheckedHandleIcon={
            <div style={{ display: "flex", alignItems: "center", justifyContent: "center", height: "100%" }}>
                <FaBellSlash style={{ color: "#8b0000" }} />
            </div>
            }
            checkedHandleIcon={
            <div style={{ display: "flex", alignItems: "center", justifyContent: "center", height: "100%" }}>
                <FaBell style={{ color: "#8b0000" }} />
            </div>
            }
        />
    );
}

export default NotificationToggle;
