/**
 * GetStarted.jsx
 *
 * This is the final step in the Rebel Remind onboarding flow.
 * It provides visual instructions to help users pin the Chrome Extension
 * to their browser toolbar and begin using it.
 *
 * 📌 Features:
 * - Scrolls to the top when mounted for a clean start
 * - Displays three-step instructions with illustrative screenshots
 * - Opens a new browser tab when onboarding is finished
 * - Automatically closes the setup tab once complete
 * - Offers navigation to return to the previous setup preferences page
 *
 * 🖼️ Images:
 * - Step 1: Extension list
 * - Step 2: Pin RebelRemind
 * - Step 3: Screenshot of the extension
 *
 * 🚀 Props: None
 * 🔁 State: None
 * 🧭 Routing: Navigates to `/setup-preferences` when "Go Back" is clicked
 * 🔧 Chrome API: Uses `chrome.tabs.create` and `chrome.tabs.remove` to manage tabs
 *
 * Authored by: Sebastian Yepez
 * Documentation generated by ChatGPT
 */

import React,  { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import "./css/WelcomePage.css";
import "./css/GetStarted.css";
import Pin from "../assets/pin.jpg"
import RebelRemind from "../assets/rebelreminduse.jpg"

const GetStarted = () => {
    const navigate = useNavigate();
    // Scroll to top on load
    useEffect(() => {
        window.scrollTo({ top: 0, behavior: "smooth" });
    }, []);

    const handleFinish = () => {
        // Open main extension page (like a dashboard or your popup's logic in tab form)
        chrome.tabs.create({ url: "chrome://newtab/" }); // open new tab

        // Close setup tab
        chrome.tabs.getCurrent((tab) => {
            if (tab?.id) {
                chrome.tabs.remove(tab.id);
            }
        });
    };

    return (
        <div className="start-page-background">
            <div className="get-started-container">
                <h1>Time to Get Started!</h1>
                <h3>Finally, here are some instructions on how to open the extension!</h3>

                <span className="instruct">1. First, open up the extensions list!</span>
                {/* First image */}
                <img
                    src="https://miro.medium.com/v2/resize:fit:1000/0*7ftPt1OUoJMOqjXN"
                    alt="Extension icon"
                    style={{ maxWidth: "500px", marginBottom: "1rem" }}
                />

                <span className="instruct">2. Then, pin RebelRemind to your toolbar!</span>
                {/* Second image */}
                <img
                    src={Pin}
                    alt="Pin RebelRemind"
                    style={{ maxWidth: "500px", marginBottom: "1rem" }}
                />

                <span className="instruct">3. Finally, open RebelRemind and enjoy!</span>
                {/* Third image */}
                <img
                    src={RebelRemind}
                    alt="RebelRemind Screenshot"
                    style={{ maxWidth: "500px", marginBottom: "1.5rem" }}
                />

                <button className="bt" style={{marginBottom: "1rem"}} onClick={handleFinish}>All Done!</button>
                <button className="bt" onClick={() => navigate("/setup-preferences")}>{'<<'} Go Back</button>
            </div>
        </div>
    );
};

export default GetStarted;

