/**
 * LoginNotificationPage Component
 *
 * This page is part of the Rebel Remind onboarding flow, prompting users to enable
 * notifications as the first step in the setup process. It provides a toggle to 
 * allow or disable notifications, with preferences stored via the Chrome Storage API.
 *
 * Features:
 * - Displays a notification opt-in page when authenticated
 * - Allows users to enable or disable notifications through the `NotificationToggle` component
 * - Saves the user's notification preference to `chrome.storage.sync`
 * - Navigates to the Preferences setup page (`/setup-preferences`) upon confirmation
 * - Shows a login prompt via `LoginButton` if the user is not authenticated
 *
 * Utilizes:
 * - `useAuth` hook to check authentication state
 * - `useNavigate` from React Router for page transitions
 * - `NotificationToggle` for enabling/disabling notifications
 * - `LoginButton` for Google-based authentication
 *
 * Authored by: Billy Estrada
 * Documentation generated by ChatGPT 4o
 *
 * @component
 * @returns {JSX.Element} The notification opt-in step of the Rebel Remind onboarding flow.
 */


import React from "react";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import Preferences from "../components/Preferences.jsx";
import LoginButton from "../components/LoginButton";
import useAuth from "../../public/hooks/useAuth";
import NotificationToggle from "../components/NotificationToggle.jsx";
import "./css/PreferencesSetup.css"

const LoginNotificationPage = () => {
    const navigate = useNavigate();
    const isAuthenticated = useAuth(); // Determines if user is logged in
   
    const [enabled, setEnabled] = useState(true);

    const submitNotifications = () => {
        chrome.storage.sync.set({ "notificationsEnabled": enabled });
        navigate("/setup-preferences");
    }

    return (
        isAuthenticated ?
            <div className="page-background">
                <div className="welcome-container">
                    <h1 style={{ textAlign: "center", marginBottom: "1rem" }}>Enable notifications?</h1>
                    <NotificationToggle
                        enabled={enabled} 
                        setEnabled={setEnabled} 
                    />
                    <p style={{ marginTop: "1rem", marginBottom: "1rem" }}>Use RebelRemind to keep up to date with UNLV events and Canvas</p>
                    <button
                        onClick={submitNotifications}
                        className="bt"
                    >
                        Continue
                    </button>
                </div>
            </div>
            :
            <>
                <div className="page-background">
                    <div className="welcome-container">
                        <h1>🛑 Before we get started...</h1>
                        <h3>Please login with Google. This will help us confirm you are a UNLV student and be used for future integrations.</h3>
                        <LoginButton />
                    </div>
            </div >
            </>
    );
};

export default LoginNotificationPage;
