/**
 * LoginNotificationPage.jsx
 *
 * This page provides a guided UI for first-time users to configure their Rebel Remind preferences.
 * It renders the Preferences component in setup mode, showing all sections and disabling 
 * interactions until their corresponding preferences are enabled.
 *
 * 🧠 Logic:
 * - If the user is authenticated via `useAuth()`, show the full preferences setup UI.
 * - If not authenticated, prompt the user to log in via Google using the `LoginButton`.
 *
 * 🧩 Components Used:
 * - <Preferences setupMode={true} />: Interactive configuration with tooltips and gated sections
 * - <LoginButton />: Triggers UNLV Google OAuth login
 *
 * 📍 Navigation:
 * - After finishing setup, users are navigated to `/get-started` for final instructions.
 *
 * 🎨 Styling:
 * - Uses `.page-background-pref` and `.preferences-container` from `LoginNotificationPage.css`
 * - Uses shared `.bt` class for consistent button styling
 *
 * Authored by: Sebastian Yepez  
 * Documentation generated by ChatGPT
 */

import React from "react";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import Preferences from "../components/Preferences.jsx";
import LoginButton from "../components/LoginButton";
import useAuth from "../../public/hooks/useAuth";
import NotificationToggle from "../components/NotificationToggle.jsx";
import "./css/PreferencesSetup.css"

const LoginNotificationPage = () => {
    const navigate = useNavigate();
    const isAuthenticated = useAuth(); // Determines if user is logged in
   
    const [enabled, setEnabled] = useState(true);

    const submitNotifications = () => {
        chrome.storage.sync.set({ "notificationsEnabled": enabled });
        navigate("/setup-preferences");
    }

    return (
        isAuthenticated ?
            <div className="page-background">
                <div className="welcome-container">
                    <h1 style={{ textAlign: "center", marginBottom: "1rem" }}>Enable notifications?</h1>
                    <NotificationToggle
                        enabled={enabled} 
                        setEnabled={setEnabled} 
                    />
                    <p style={{ marginTop: "1rem", marginBottom: "1rem" }}>Use RebelRemind to keep up to date with UNLV events and Canvas</p>
                    <button
                        onClick={submitNotifications}
                        className="bt"
                    >
                        Continue
                    </button>
                </div>
            </div>
            :
            <>
                <div className="page-background">
                    <div className="welcome-container">
                        <h1>🛑 Before we get started...</h1>
                        <h3>Please login with Google. This will help us confirm you are a UNLV student and be used for future integrations.</h3>
                        <LoginButton />
                    </div>
            </div >
            </>
    );
};

export default LoginNotificationPage;
