/**
 * PreferencesSetup.jsx
 *
 * This page provides a guided UI for first-time users to configure their Rebel Remind preferences.
 * It renders the Preferences component in setup mode, showing all sections and disabling 
 * interactions until their corresponding preferences are enabled.
 *
 * 🧠 Logic:
 * - If the user is authenticated via `useAuth()`, show the full preferences setup UI.
 * - If not authenticated, prompt the user to log in via Google using the `LoginButton`.
 *
 * 🧩 Components Used:
 * - <Preferences setupMode={true} />: Interactive configuration with tooltips and gated sections
 * - <LoginButton />: Triggers UNLV Google OAuth login
 *
 * 📍 Navigation:
 * - After finishing setup, users are navigated to `/get-started` for final instructions.
 *
 * 🎨 Styling:
 * - Uses `.page-background-pref` and `.preferences-container` from `PreferencesSetup.css`
 * - Uses shared `.bt` class for consistent button styling
 *
 * Authored by: Sebastian Yepez  
 * Documentation generated by ChatGPT
 */

import React from "react";
import { useNavigate } from "react-router-dom";
import Preferences from "../components/Preferences.jsx";
import LoginButton from "../components/LoginButton";
import useAuth from "../../public/hooks/useAuth";
import "./css/PreferencesSetup.css"

const PreferencesSetup = () => {
    const navigate = useNavigate();
    const isAuthenticated = useAuth(); // Determines if user is logged in

    return (
        isAuthenticated ?
            <div className="page-background-pref">
                <div className="preferences-container">
                    <h1 style={{ textAlign: "center", marginBottom: "1rem" }}>🛠️ Setup Your Rebel Remind Preferences</h1>
                    <p style={{ textAlign: "center", color: "#555", marginBottom: "2rem" }}>
                        Select what you'd like Rebel Remind to notify you about. You can change these anytime!
                    </p>

                    {/* Preferences component */}
                    <Preferences setupMode={true} />

                    <p style={{ marginBottom: "0.25rem" }}>All done? Let's go!</p>
                    <p style={{ marginBottom: "1rem" }}>Remember, you can always edit your preferences from your settings.</p>
                    <button
                        onClick={() => navigate("/get-started")}
                        className="bt"
                    >
                        Finish Setup
                    </button>
                </div>
            </div>
            :
            <>
                <div className="page-background">
                    <div className="welcome-container">
                        <h1>🛑 Before we get started...</h1>
                        <h3>Please login with Google. This will help us confirm you are a UNLV student and be used for future integrations.</h3>
                        <LoginButton />
                    </div>
            </div >
            </>
    );
};

export default PreferencesSetup;
