/**
 * PreferencesSetup.jsx
 *
 * This page provides a guided UI for first-time users to configure their Rebel Remind preferences.
 * It renders the Preferences component in setup mode, showing all sections and disabling 
 * interactions until their corresponding preferences are enabled.
 *
 * 🧩 Components Used:
 * - <Preferences setupMode={true} />: Interactive configuration with tooltips and gated sections
 *
 * 📍 Navigation:
 * - After finishing setup, users are navigated to `/get-started` for final instructions.
 *
 * 🎨 Styling:
 * - Uses `.page-background-pref` and `.preferences-container` from `PreferencesSetup.css`
 * - Uses shared `.bt` class for consistent button styling
 *
 * Authored by: Sebastian Yepez  
 * Documentation generated by ChatGPT
 */

import React from "react";
import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import Preferences from "../components/Preferences.jsx";
import LoginButton from "../components/LoginButton";
import "./css/PreferencesSetup.css"

const PreferencesSetup = () => {
    const navigate = useNavigate();
    const [isNotificationsEnabled, setIsNotificationsEnabled] = useState(null);

    useEffect(() => {
        chrome.storage.sync.get("notificationsEnabled", (data) => {
          if (data && data.notificationsEnabled !== undefined) {
            setIsNotificationsEnabled(data.notificationsEnabled);
          } else {
            setIsNotificationsEnabled(false);
          }
        });
      }, []);

    return (
            <div className="page-background-pref">
                <div className="preferences-container">
                    
                    <h1 style={{ textAlign: "center", marginBottom: "1rem" }}>🛠️ Setup Your Rebel Remind Preferences</h1>
                    { isNotificationsEnabled ? (
                    <>
                        <p style={{ textAlign: "center", color: "#555", marginBottom: "2rem" }} >
                            Thanks for enabling notifications! 
                        </p>
                        <p style={{ textAlign: "center", color: "#555", marginBottom: "2rem" }}>
                            Select what you'd like Rebel Remind to notify you about. You can change these anytime!
                        </p>
                    </>
                    ):(
                    <>
                        <p> No notifications... No problem! </p>
                        <p style={{ textAlign: "center", color: "#555", marginBottom: "2rem" }}>
                            We still will keep your RebelRemind up to date with upcoming events, but won't push any notifications.
                        </p>
                        <p style={{ textAlign: "center", color: "#555", marginBottom: "2rem" }}>
                            Select what preferences interest you. You can change these anytime!
                        </p>
                    </>
                    )}
                    {/* Preferences component */}
                    <Preferences setupMode={true} />

                    <p style={{ marginBottom: "0.25rem" }}>All done? Let's go!</p>
                    <p style={{ marginBottom: "1rem" }}>Remember, you can always edit your preferences from your settings.</p>
                    <button
                        onClick={() => navigate("/get-started")}
                        className="bt"
                    >
                        Finish Setup
                    </button>
                </div>
            </div>
    );
};

export default PreferencesSetup;
