/**
 * Welcome.jsx
 *
 * This component is the landing page for new users of the Rebel Remind extension.
 * It acts as the entry point to the onboarding/setup flow after installation.
 *
 * 🎯 Purpose:
 * - Greets users with a welcome message
 * - Provides a call-to-action button that navigates to the preferences setup page
 *
 * ✨ Features:
 * - Simple layout styled via `WelcomePage.css`
 * - Button navigation using React Router to `/setup-preferences`
 *
 * 🚀 Props: None
 * 🧭 Routing: Navigates to the setup flow when "Get Started" is clicked
 *
 * Authored by: Sebastian Yepez  
 * Documentation generated by ChatGPT
 */

import React from "react";
import { useNavigate } from "react-router-dom";
import "./css/WelcomePage.css";

const Welcome = () => {
  const navigate = useNavigate();

  return (
    <div className="page-background">
      <div className="welcome-container">
        <h1>🎉 Welcome to Rebel Remind!</h1>
        <h3>Thanks for installing the extension. Let’s get started!</h3>
        <button onClick={() => navigate("/login-notification")}>Get Started</button>
      </div>
    </div>
  );
};

export default Welcome;
